
pipelines:
  - name: embedTest
    steps:
      - name: triggerTest
        type: TriggerPipeline
        configuration:
          pipelineName: testPipeline # required
          stepName: myStep # required. will fail the step if ambiguous
          branchName: feature/pipe-1234 # optional. May be necessary if other criteria are too ambiguous. No default.
          projectKey: ${project_key} # optional. Default is current project.
          integrations:
            - name: pipAccess
        execution:
          onStart:
            - echo “triggering the nested run”
          onSuccess:
            - echo “it worked! $nested_run_status”
          onFailure:
            - echo “it failed... $nested_run_status”
          onComplete:
            - echo “sending some messages...”
