resources:
  - name: propertyCanvas
    type: PropertyBag
    configuration:
      key1: value1
      key2: value2
      pipelines: "user_in"
  - name: propertyCanvas2
    type: PropertyBag
    configuration:
      key1: value1
      key2: value2
pipelines:
  - name: single_test
    configuration:
      environmentVariables:
        readOnly:
          pipevar1: 1
          pipevar2: 2
    steps:
      - name: trigger_1
        type: Bash
        configuration:
          affinityGroup: trigger
          environmentVariables:
            env1: 1
            env2:
              default: 2
              description: someDescription
          priority: 0
        execution:
          onExecute:
            - printenv
            - echo "done"
  - name: trigger_test
    configuration:
      environmentVariables:
        readOnly:
          pipevar1: 1
          pipevar2: 2
    steps:
      - name: trigger_1
        type: Bash
        configuration:
          affinityGroup: trigger
          timeoutSeconds: 10
          environmentVariables:
            env1: 1
            env2:
              default: 2
              description: someDescription
          priority: 0
          inputResources:
# #             - name: buildInfoTrigger
# #             - name: gitResCanvas
            - name: propertyCanvas2
            - name: propertyCanvas
              trigger: false
        execution:
          onExecute:
            - printenv
            - echo "done"
            - sleep 20
#       - name: jenkins
#         type: Jenkins
#         configuration:
#           jenkinsJobName: somename
#           integrations:
#             - name: jenkins
      - name: trigger_2
        type: Bash
        configuration:
          affinityGroup: g1
          environmentVariables:
            step2env1: 1
            step2env2: 2
          inputSteps:
            - name: trigger_1
#             - name: jenkins
#           inputResources:
#             - name: propertyCanvas2
#             - name: buildInfoTrigger
#             - name: gitResCanvas
#           outputResources:
#             - name: propertyCanvas
        execution:
          onExecute:
#             - printenv
#             - echo "done"
#             - write_output propertyCanvas "description=\"hello world\""
#             - add_pipeline_variables prev_runid=$run_id
#             - touch testreport.xml
#             - save_tests testreport.xml
            - echo runs > cache.file
            - add_cache_files cache.file runs.file
            - echo "state=pipeline2" > cache.txt
            - add_run_files cache.txt run_state_file
            - add_pipeline_files cache.txt pipe_state_file
            - write_output propertyCanvas "pipelines=$run_id"
            - save_tests cache.txt
            - sleep 100
