pipelines:
  - name: github_demo_test
    steps:
      - name: step_one
        type: Bash
        execution:
          onExecute:
            - echo "done"
      - name: step_twoss
        type: Bash
        configuration:
          inputSteps:
            - name: step_one
        execution:
          onExecute:
            - echo "test"