resources:
  - name: propertyCanvas
    type: PropertyBag
    configuration:
      key1: value1
      key2: value2
      pipelines: "user_in"
  - name: propertyCanvasOut
    type: PropertyBag
    configuration:
      key1: value1
      key2: value2
      pipelines: "user_in"
  - name: art
    type: BuildInfo
    configuration:
      sourceArtifactory: art
      buildName: artBuild
      buildNumber: 1
  - name: gitPip
    type: GitRepo
    configuration:
      gitProvider: git
      path: ChaitanyaVootla/ymlTest
pipelines:
  - name: single_test
    configuration:
      environmentVariables:
        readOnly:
          pipevar1: 1
          pipevar2: 2
    steps:
      - name: trigger_1
        type: Bash
        configuration:
          affinityGroup: trigger
          environmentVariables:
            env1: 1
            env2:
              default: 2
              description: someDescription
          priority: 0
        execution:
          onExecute:
            - printenv
            - echo "done"
  - name: trigger_test
    configuration:
      environmentVariables:
        readOnly:
          pipevar1: 1
          pipevar2: 2
    steps:
      - name: trigger_1
        type: Bash
        configuration:
          affinityGroup: trigger
          environmentVariables:
            env1: 1
            env2:
              default: 2
              description: someDescription
          priority: 0
          inputResources:
# #             - name: buildInfoTrigger
            - name: art
            - name: propertyCanvas
              trigger: false
            - name: gitPip
          outputResources:
            - name: propertyCanvasOut
        execution:
          onExecute:
#             - echo runs > summaryOutput.json
#             - save_artifact_info buildInfo summaryOutput.json --build-name=$JFROG_CLI_BUILD_NAME --build-number=$JFROG_CLI_BUILD_NUMBER
            - echo "done"
#       - name: jenkins
#         type: Jenkins
#         configuration:
#           jenkinsJobName: somename
#           integrations:
#             - name: jenkins
