valuesFilePath: ./values.yaml

pipelines:
  - name: {{ .Values.pipeline.name }}
    steps:
      - name: {{ .Values.pipeline.step_identifier }}
        type: Bash
        execution:
          onExecute:
            - echo "branch is {{gitBranch}}"
