valuesFilePath: ./values.yaml

pipelines:
  - name: values_test_2
    steps:
      - name: "{{ .Values.stepName }}"
        type: Bash
        execution:
          onExecute:
            - echo "done 2"
