valuesFilePath: ./values.yaml

pipelines:
  - name: values_test_2
    steps:
      - name: {{ .Values.stepName }}
        type: Bash
        execution:
          onExecute:
            - echo "branch is {{gitBranch}}"
            - echo "root bucket is {{.jfrog-pipelines.rootBucket}}"
            - echo "source repo is {{.jfrog-pipelines.sourceRepository}}"
            - echo "rt token is {{.jfrog-pipelines.localArtifactory}}"
