pipelines:
  - name: demo_test_github
    steps:
      - name: step_one
        type: Bash
        execution:
          onExecute:
            - echo "asd"
      - name: step_two
        type: Bash
        configuration:
          inputSteps:
            - name: step_one
        execution:
          onExecute:
            - echo "two"
